"use strict";
// Mechanical export of verified client field definitions and local capture/config data.
const fs = require('fs');
const path = require('path');
const {Schema, Decoder, parseFrame, framePayload, extractWsMessages, directionOf} = require('./har_decode');
const root = path.resolve(__dirname, '..');
const schema = new Schema('D:/doudi-resources/client-analysis/decompiled-gameplay-runtime-6.9.263'); schema.load();
const decoder = new Decoder(schema);
const configRoot = 'D:/doudi-resources/client-analysis/config-json/6.9.263';
const snapshot = JSON.parse(fs.readFileSync('D:/doudi-resources/client-analysis/luban-6.9.263-20260908/manifest.json','utf8'));
if (snapshot.version !== '6.9.263' || snapshot.rawDataCount !== 722) throw Error('Unexpected Luban snapshot');
const rows = n => {
  if (!snapshot.rawData.some(r=>r.key===n)) throw Error('Missing snapshot table '+n);
  const table = JSON.parse(fs.readFileSync(path.join(configRoot, n+'.json'), 'utf8'));
  if (table.file !== n || table.rowCount !== table.rows.length) throw Error('Invalid table '+n);
  return table.rows;
};
const capture = JSON.parse(fs.readFileSync('D:/抓包数据/第二次抓包.json', 'utf8')).messages;
const protoRoot = path.join(root, 'dpcq-protobuf/src/main/proto');
const existing = new Map();
for (const f of fs.readdirSync(protoRoot).filter(f => f.endsWith('.proto') && f !== 'chapter17.proto')) {
  for (const m of fs.readFileSync(path.join(protoRoot,f),'utf8').matchAll(/message\s+(\w+)/g)) existing.set(m[1],f);
}
const wanted = ['FireTowerInfoResp','FireTowerChallengeReq','FireTowerChallengeResp',
  'FireTowerChallengeAfterReq','FireTowerChallengeAfterResp','FireTowerSeeCGReq','FireTowerSeeCGResp',
  'FireTowerInReq','FireTowerHostReq','FireTowerHostResp','FireTowerHostEndResp',
  'FireTowerHostResultReq','FireTowerHostResultResp','FireTowerGiftInfoReq','FireTowerGiftInfoResp',
  'FireTowerTimeRewardUpdateResp','PrePareFightReq','PrePareFightResp',
  'MainMapTakeHangUpMainEquipRewardReq','MainMapHangUpRewardUpdateResp',
  'PlayerCommonSkillResp','CommonSkillLevelUpResp','UniversalSkillLotteryVo',
  'ChangeFightValueActionVO','CommSkillActionResp'];
const primitive={int:'int32',long:'int64',float:'float',double:'double',bool:'bool',string:'string',bytes:'bytes',uint:'uint32',ulong:'uint64'};
const generated=new Map(),imports=new Set();
function visit(name){
  if(existing.has(name)){imports.add(existing.get(name));return;}
  if(generated.has(name))return;
  const fields=schema.messages.get(name); if(!fields)throw Error('Missing client schema '+name);
  generated.set(name,fields);
  for(const f of fields.values())if(!primitive[f.type]&&!schema.enums.has(f.type))visit(f.type);
}
wanted.forEach(visit);
const snake=n=>n.replace(/[A-Z]/g,c=>'_'+c.toLowerCase());
let definitions=[];
for(const [name,fields]of generated){
  const id=[...schema.protocolNames].find(([k,v])=>v===name)?.[0];
  definitions.push('message '+name+' {',...(id?['    enum Proto { UNKNOWN = 0; ID = '+id+'; }']:[]));
  for(const [n,f]of fields)definitions.push('    '+(f.repeated?'repeated ':'')+(primitive[f.type]||(schema.enums.has(f.type)?'int32':f.type))+' '+snake(f.name)+' = '+n+';');
  definitions.push('}','');
}
fs.writeFileSync(path.join(protoRoot,'chapter17.proto'),
  '// Generated by tools/export_ch17_support.js from client ProtoMember definitions.\nsyntax = "proto3";\npackage doupo;\noption java_package = "com.doupo.protocol";\noption java_multiple_files = true;\n'+[...imports].map(f=>'import "'+f+'";').join('\n')+'\n\n'+definitions.join('\n'));
const data={
  source:'第二次抓包.json / 6.9.263 Luban',
  configVersion:snapshot.version,
  provenance:{catalogSha256:snapshot.catalogSha256,resourceVersion:snapshot.resourceVersion,
    patchAssemblyVersion:snapshot.patchAssemblyVersion,assemblyManifestVersion:snapshot.assemblyManifestVersion,
    configsDllSha256:snapshot.dlls.find(d=>d.name==='SGEngine.Configs.Runtime.dll').decodedSha256,
    gameplayDllSha256:snapshot.dlls.find(d=>d.name==='SGEngine.Gameplay.Runtime.dll').decodedSha256},
  tasks:rows('taskconfig').filter(r=>r.TaskId>=200001&&r.TaskId<=200111),
  chapters:rows('mainstageconfig').filter(r=>r.Id>=10100101&&r.Id<=10300801),
  tower:rows('powertowerconfig').filter(r=>r.Id<=19),
  towerChapters:rows('powertowerchapterconfig'),
  towerRewards:rows('powertowerrewardconfig'),
  reputation:rows('reputationconfig').filter(r=>r.Id<=1003),
  levels:rows('playerlevelconfig').filter(r=>r.Level>=1&&r.Level<=17),
  stages:rows('playerstagetaskconfig').filter(r=>r.Id<=3),
  lotteryPools:rows('newskilllotterypoolconfig'),
  mainEquips:rows('mainequipconfig'),
  lotteryTypes:rows('lotterytypeconfig').filter(r=>[12,13].includes(r.Id)),
  elixirBase:rows('exppoolbaseconfig').filter(r=>r.Key<=2),
  elixirAccumulate:rows('exppoolaccumulateconfig').filter(r=>[1,1101,1102].includes(r.Key)),
  towerHost:[],
};
const crypto = require('crypto');
const tableNames = ['taskconfig','mainstageconfig','powertowerconfig','powertowerchapterconfig',
  'powertowerrewardconfig','reputationconfig','playerlevelconfig','playerstagetaskconfig',
  'newskilllotterypoolconfig','lotterytypeconfig','exppoolbaseconfig','exppoolaccumulateconfig',
  'mainequipconfig'];
data.provenance.tables = tableNames.map(name=>({name,
  jsonSha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(configRoot,name+'.json'))).digest('hex'),
  rawData:snapshot.rawData.find(r=>r.key===name)}));
let lastPass=2, start=Date.parse(capture.find(m=>m.name==='FireTowerHostResp').time);
for(const m of capture.filter(m=>m.name==='FireTowerInfoResp'&&m.decoded.hosting)){
  const pass=m.decoded.chapters[0].passNum;
  if(pass<=lastPass)continue;
  data.towerHost.push({pass,idx:m.idx,afterMs:Date.parse(m.time)-start});lastPass=pass;
}
const res=path.join(root,'dpcq-game-server/src/main/resources/chapter17');fs.mkdirSync(res,{recursive:true});
fs.writeFileSync(path.join(res,'config.json'),JSON.stringify(data,null,2));
// Preserve exact binary preview/lottery messages; never serialize decoded JS int64 numbers.
const har=JSON.parse(fs.readFileSync('C:/Users/ppp/Desktop/imlj2-cn-gamewx.lansors.com_2026_09_07_19_03_22.har','utf8'));
const messages=extractWsMessages(har);let auth=false;
const selected = new Set([9503,9510,9554,9569,10136,10164,10165,10166,10168,10171,10174,10177,9886]);
const equipFixtures = new Set([9126,9127,9128,10060,10061,10062,10063]);
const equipTestRes = path.join(root,'dpcq-game-server/src/test/resources/main-equip');
fs.mkdirSync(equipTestRes,{recursive:true});
for(let i=0;i<messages.length;i++){
  const [payload]=framePayload(messages[i]);if(!payload)continue;
  let f;try{f=parseFrame(payload,directionOf(messages[i]),auth);}catch{continue;}
  if(f.protocolId===50052)auth=true;
  if(equipFixtures.has(i)) fs.writeFileSync(path.join(equipTestRes,i+'-'+f.protocolId+'.bin'),f.body);
  if(selected.has(i)){
    fs.writeFileSync(path.join(res, i+'-'+f.protocolId+'.bin'),f.body);
    console.log('fixture',i,f.protocolId,schema.protocolNames.get(f.protocolId));
  }
}
console.log('messages',generated.size,'towerHost',data.towerHost,'levels',data.levels.length);
