"use strict";
// Mechanical exports from the local 6.9 client, Luban snapshot and second capture.
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const {Schema, parseFrame, framePayload, extractWsMessages, directionOf} = require('./har_decode');
const root = path.resolve(__dirname, '..');
const schema = new Schema('D:/doudi-resources/client-analysis/decompiled-gameplay-runtime-6.9.263');
schema.load();
const protoRoot = path.join(root, 'dpcq-protobuf/src/main/proto');
const existing = new Map();
for (const file of fs.readdirSync(protoRoot).filter(f => f.endsWith('.proto') && f !== 'continuation.proto')) {
  for (const m of fs.readFileSync(path.join(protoRoot, file), 'utf8').matchAll(/message\s+(\w+)/g)) existing.set(m[1], file);
}
const primitive = {int:'int32',long:'int64',float:'float',double:'double',bool:'bool',string:'string',bytes:'bytes',uint:'uint32',ulong:'uint64'};
const generated = new Map(), imports = new Set();
function visit(name) {
  if (existing.has(name)) { imports.add(existing.get(name)); return; }
  if (generated.has(name)) return;
  const fields = schema.messages.get(name);
  if (!fields) throw Error('Missing client schema ' + name);
  generated.set(name, fields);
  for (const f of fields.values()) if (!primitive[f.type] && !schema.enums.has(f.type)) visit(f.type);
}
['ChangeNameReq','ChangeNameResp','MainEquipLevelUpReq','MainEquipLevelUpResp',
 'MainEquipDecomposeReq','MainEquipDecomposeResp'].forEach(visit);
const definitions = [];
for (const [name, fields] of generated) {
  const id = [...schema.protocolNames].find(([k,v]) => v === name)?.[0];
  definitions.push('message ' + name + ' {', ...(id ? ['    enum Proto { UNKNOWN = 0; ID = ' + id + '; }'] : []));
  for (const [n,f] of fields) definitions.push('    ' + (f.repeated ? 'repeated ' : '')
    + (primitive[f.type] || (schema.enums.has(f.type) ? 'int32' : f.type)) + ' '
    + f.name.replace(/[A-Z]/g, c => '_' + c.toLowerCase()) + ' = ' + n + ';');
  definitions.push('}', '');
}
fs.writeFileSync(path.join(protoRoot, 'continuation.proto'), '// Generated by tools/export_ch18_support.js from 6.9 client ProtoMember definitions.\n'
  + 'syntax = "proto3";\npackage doupo;\noption java_package = "com.doupo.protocol";\noption java_multiple_files = true;\n'
  + [...imports].map(f => 'import "' + f + '";').join('\n') + '\n\n' + definitions.join('\n'));
const configRoot = 'D:/doudi-resources/client-analysis/config-json/6.9.263';
const provenance = [];
function rows(name) {
  const bytes = fs.readFileSync(path.join(configRoot, name + '.json'));
  const table = JSON.parse(bytes);
  if (table.file !== name || table.rowCount !== table.rows.length) throw Error('Invalid table ' + name);
  provenance.push({name, sha256: crypto.createHash('sha256').update(bytes).digest('hex')});
  return table.rows;
}
const capture = JSON.parse(fs.readFileSync('D:/抓包数据/第二次抓包.json', 'utf8')).messages;
const transitions = [];
for (const m of capture) {
  if (m.name !== 'MainMapPassChapterUpdateResp') continue;
  const d = m.decoded;
  if (d.mainMapChapterId < 10300801 || d.mainMapChapterId > 10400101
      || transitions.some(t => t.chapterId === d.mainMapChapterId)) continue;
  transitions.push({chapterId:d.mainMapChapterId,idx:m.idx,stageTime:d.stageTime,
    lastStageTime:d.lastStageTime,loseBackId:d.loseBackId});
}
const data = {source:'第二次抓包.json / 6.9.263 Luban',
  chapters:rows('mainstageconfig').filter(r => r.Id >= 10300801 && r.Id <= 10400101),
  equipStrengthNeed:rows('mainequipstrengtheneedconfig'),
  equipStrengthMaterial:rows('mainequipstrengthematerialconfig'),
  nameSettings:rows('configvalueconfig').filter(r => ['word.maxNameLength','changeNameConsumeResource'].includes(r.Id)),
  transitions,provenance};
const res = path.join(root, 'dpcq-game-server/src/main/resources/chapter17');
fs.writeFileSync(path.join(res, 'continuation.json'), JSON.stringify(data, null, 2));
const har = JSON.parse(fs.readFileSync('C:/Users/ppp/Desktop/imlj2-cn-gamewx.lansors.com_2026_09_07_19_03_22.har', 'utf8'));
const messages = extractWsMessages(har);
const selected = new Set([10205,10206,10536]);
const testIds = new Set([10116,10117,10436,10438,10458,10460,10461,10463,10533,10536,10548]);
const testRes = path.join(root, 'dpcq-game-server/src/test/resources/continuation');
fs.mkdirSync(testRes, {recursive:true});
let auth = false;
for (let i = 0; i < messages.length; i++) {
  const [payload] = framePayload(messages[i]);
  if (!payload) continue;
  let frame;
  try { frame = parseFrame(payload, directionOf(messages[i]), auth); } catch { continue; }
  if (frame.protocolId === 50052) auth = true;
  if (selected.has(i)) fs.writeFileSync(path.join(res, i + '-' + frame.protocolId + '.bin'), frame.body);
  if (testIds.has(i)) fs.writeFileSync(path.join(testRes, i + '-' + frame.protocolId + '.bin'), frame.body);
}
console.log('Generated messages:', [...generated.keys()], 'transitions:', transitions);
