<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.doupo</groupId>
        <artifactId>doupo-server</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>dpcq-game-server</artifactId>

    <dependencies>
        <dependency>
            <groupId>com.doupo</groupId>
            <artifactId>dpcq-common</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.doupo</groupId>
            <artifactId>dpcq-protobuf</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.doupo</groupId>
            <artifactId>dpcq-pojo</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>game</groupId>
            <artifactId>gaming-ruler</artifactId>
            <version>0.0.1</version>
        </dependency>
        <dependency>
            <groupId>game</groupId>
            <artifactId>gaming-fakecmd</artifactId>
            <version>0.0.1</version>
        </dependency>
        <dependency>
            <groupId>gaming-project</groupId>
            <artifactId>gaming-prefab</artifactId>
            <version>0.0.1</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-crypto</artifactId>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
